In [154]:
import pandas as pd
import datetime
from datetime import timedelta

In [155]:
DATASET_PATH = 'data/'
AUTH_FILTERED_PATH = 'data/authority_filtered/'
SPIKES_PATH = 'data/spikes/'

In [156]:
AUTH_FILTERED_DATASET = pd.read_csv(AUTH_FILTERED_PATH + 'ferrero_corp_auth.csv')
SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_spikes.csv')
AUTH_SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_auth_spikes.csv')
MERGED_SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_merged.csv')

START_DATE = '2019-10-16'
END_DATE = '2019-10-23'
DATES_DELTA = 7

In [157]:
auth_filtered_df = AUTH_FILTERED_DATASET.copy()
auth_filtered_df['date_index'] = pd.to_datetime(auth_filtered_df['date_index'])
# auth_filtered_df.set_index('id', inplace=True)
auth_filtered_df

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
0,34648,twitter,1174618145786650624,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,La Ferrero riconosce a 6000 dipendenti un prem...,https://t.co/T3wBQLWAeo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-19 09:36:03+00:00
1,34065,twitter,1176441842096910336,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Il Ministro Fioramonti si permette di giustifi...,NaN,@lofioramonti,NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-24 10:22:47+00:00
2,33847,twitter,1176748033066844160,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@theoddmother @lofioramonti In Italia la Ferre...,NaN,"@theoddmother, @lofioramonti",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-25 06:39:28+00:00
3,32534,twitter,1183821988437135362,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@gianni_la_marca @angelofilippi Per il mercato...,NaN,"@gianni_la_marca, @angelofilippi",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-10-14 19:08:51+00:00
4,32064,twitter,1186949229438263297,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Siamo in un pericoloso paradosso con il Paese ...,https://t.co/lkkYO9w8VC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-23 10:15:23+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1013,twitter,1418810115445166080,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, la strategia green del big di Alba (Ã¨...","https://t.co/r2XvO05KdN, https://t.co/t8k8vmUlQk",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-24 05:47:46+00:00
279,841,twitter,1420717382830415880,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Ferrero l'azienda meglio percepita sul territo...,"https://t.co/4O4c31bPiq, https://t.co/n8RpxZP5Vu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-29 12:06:34+00:00
280,822,twitter,1421105542945202182,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Lâattimo fuggente, online il numero di agosto ...",https://t.co/Q9FPElZrOU,"@ferrero_eu, @generali, @prada, @armani, @ciro...","#luigicremonini, #vincenzocremonini, #alberton...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30 13:48:58+00:00
281,467,twitter,1426075939201421313,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Mediobanca, Gavio arrotonda la quota. I Ferrer...","https://t.co/QPX7deAYBt, https://t.co/XUfJMFKsFE",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-13 06:59:33+00:00
282,61,twitter,1430765728890859524,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Da anni le aziende alimentari prendono impegni...,"https://t.co/79pL8eW8Dm, https://t.co/3MC4xgol6A",@foodwatch_de,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26 05:35:06+00:00

In [158]:
spikes_df = SPIKES_DATASET.copy()
spikes_df['date_index'] = pd.to_datetime(spikes_df['date_index'])
spikes_df.set_index('date_index', inplace=True)
spikes_df

                              mIndex  volume  sentiment   sign
date_index
2019-08-20 00:00:00+00:00   2.602240      96   0.373657  False
2019-08-21 00:00:00+00:00  13.554951     378   0.373657  False
2019-08-22 00:00:00+00:00   5.825910     179   0.373657  False
2019-08-23 00:00:00+00:00   2.485722      93   0.373657  False
2019-08-24 00:00:00+00:00   1.006199      71   0.373657  False
...                              ...     ...        ...    ...
2021-08-19 00:00:00+00:00   0.774941      36   0.524922   True
2021-08-20 00:00:00+00:00   0.858849      38   0.493919  False
2021-08-23 00:00:00+00:00   2.040529      67   0.468272  False
2021-08-24 00:00:00+00:00   1.287879      49   0.360722  False
2021-08-25 00:00:00+00:00   0.679956      41   0.437569  False

[165 rows x 4 columns]

In [159]:
auth_spikes_df = AUTH_SPIKES_DATASET.copy()
auth_spikes_df.set_index('date_index', inplace=True)
auth_spikes_df

                           mIndex  volume  sentiment   sign
date_index
2019-08-15 00:00:00+00:00     inf       2   0.393990  False
2019-08-19 00:00:00+00:00     inf       1   0.393990  False
2019-08-21 00:00:00+00:00     inf       1   0.393990  False
2019-08-22 00:00:00+00:00     inf       1   0.393990  False
2019-08-23 00:00:00+00:00     inf       1   0.393990  False
...                           ...     ...        ...    ...
2021-07-24 00:00:00+00:00     inf       1   0.895521   True
2021-07-29 00:00:00+00:00     inf       1   0.478257  False
2021-07-30 00:00:00+00:00     inf       1   0.719718   True
2021-08-13 00:00:00+00:00     inf       1   0.183895  False
2021-08-26 00:00:00+00:00     inf       1   0.000000  False

[165 rows x 4 columns]

In [160]:
merged_spikes_df = MERGED_SPIKES_DATASET.copy()
merged_spikes_df.set_index('date_index', inplace=True)
merged_spikes_df

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-08-14 00:00:00+00:00,0.648969,24,0.373657,False,NaN,0.0,NaN,False
2019-08-15 00:00:00+00:00,1.299904,48,0.373657,False,inf,2.0,0.39399,False
2019-08-16 00:00:00+00:00,0.757970,27,0.373657,False,NaN,0.0,NaN,False
2019-08-18 00:00:00+00:00,0.786786,26,0.373657,False,NaN,0.0,NaN,False
2019-08-19 00:00:00+00:00,0.712039,22,0.373657,False,inf,1.0,0.39399,False
...,...,...,...,...,...,...,...,...
2021-08-23 00:00:00+00:00,2.943833,67,0.468272,False,NaN,0.0,NaN,False
2021-08-24 00:00:00+00:00,2.191184,49,0.360722,False,NaN,0.0,NaN,False
2021-08-25 00:00:00+00:00,1.583260,41,0.437569,False,NaN,0.0,NaN,False
2021-08-26 00:00:00+00:00,1.332765,39,0.406829,False,inf,1.0,0.00000,False
2021-08-27 00:00:00+00:00,0.731694,24,0.298725,False,NaN,NaN,NaN,NaN

In [161]:
def get_relevance_idxs(df, thresh):
    return df[df['mIndex'] > thresh][['mIndex', 'sign']]


def filter_by_relevance_idxs(df, col='mIndex', thresh=0.5):
    return df[df[col] > thresh]


def get_date_range(date, d_range):
    date_list = []
    date_list.append(date)
    for day in range(1, d_range+1):
        b_date = (date - datetime.timedelta(days = day))
        a_date = (date + datetime.timedelta(days = day))
        date_list.append(b_date)
        date_list.append(a_date)
        date_list.sort()
    return date_list


# The cast needs to be handled more elegantly
def filter_by_previous_dates(df, date, date_range):
    mindate = str((pd.to_datetime(date, format='%Y/%m/%d', errors='coerce') - pd.to_timedelta(date_range, unit='days')).date())
    lowerbound = df[df.index > mindate]    
    return lowerbound[lowerbound.index < date]


def get_previous_dates(date, date_range):
    date_list = []
    date_list.append(date)
    for day in range(1, date_range+1):
        b_date = (date - datetime.timedelta(days = day))
        date_list.append(b_date)
        date_list.sort()
    return date_list


# def get_volumes_in_range(df, days_range):
#     spikes = get_days_left(iris_join, 0.5)
#     days_range = timedelta(days=days_range)
#     for date in spikes['date_index']:


def filter_by_date_range(dataset, mindate, maxdate):
    lowerbound = dataset[dataset.index > mindate]    
    return lowerbound[lowerbound.index < maxdate]

In [162]:
date = pd.to_datetime(END_DATE)
date_range = get_previous_dates(date, 7)
date_range_idx = pd.to_datetime(date_range, utc=True)
date_range_idx = pd.DataFrame(date_range_idx, columns=['date'])
date_range_idx

                       date
0 2019-10-16 00:00:00+00:00
1 2019-10-17 00:00:00+00:00
2 2019-10-18 00:00:00+00:00
3 2019-10-19 00:00:00+00:00
4 2019-10-20 00:00:00+00:00
5 2019-10-21 00:00:00+00:00
6 2019-10-22 00:00:00+00:00
7 2019-10-23 00:00:00+00:00

In [163]:
filtered_merged_spikes_df = filter_by_date_range(merged_spikes_df, START_DATE, END_DATE)
filtered_merged_spikes_df

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-10-16 00:00:00+00:00,0.844729,79,0.413103,False,NaN,0.0,NaN,False
2019-10-17 00:00:00+00:00,0.561724,58,0.381491,False,1.100317,1.0,0.600317,True
2019-10-20 00:00:00+00:00,0.759148,64,0.384685,False,NaN,0.0,NaN,False
2019-10-21 00:00:00+00:00,0.514465,42,0.430693,False,NaN,0.0,NaN,False

In [164]:
filter_by_relevance_idxs(merged_spikes_df, 'mIndex_x', 0.5)

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-08-14 00:00:00+00:00,0.648969,24,0.373657,False,NaN,0.0,NaN,False
2019-08-15 00:00:00+00:00,1.299904,48,0.373657,False,inf,2.0,0.39399,False
2019-08-16 00:00:00+00:00,0.757970,27,0.373657,False,NaN,0.0,NaN,False
2019-08-18 00:00:00+00:00,0.786786,26,0.373657,False,NaN,0.0,NaN,False
2019-08-19 00:00:00+00:00,0.712039,22,0.373657,False,inf,1.0,0.39399,False
...,...,...,...,...,...,...,...,...
2021-08-23 00:00:00+00:00,2.943833,67,0.468272,False,NaN,0.0,NaN,False
2021-08-24 00:00:00+00:00,2.191184,49,0.360722,False,NaN,0.0,NaN,False
2021-08-25 00:00:00+00:00,1.583260,41,0.437569,False,NaN,0.0,NaN,False
2021-08-26 00:00:00+00:00,1.332765,39,0.406829,False,inf,1.0,0.00000,False
2021-08-27 00:00:00+00:00,0.731694,24,0.298725,False,NaN,NaN,NaN,NaN

In [168]:
auth_tweets = {}
auth_filtered_df['id'] = auth_filtered_df['id'].map(str)
auth_tweets = auth_filtered_df.groupby(pd.Grouper(key='date_index', freq='d')).agg({'id': ' '.join})
auth_tweets

                                            id
date_index
2019-08-02 00:00:00+00:00  1157355441531305984
2019-08-03 00:00:00+00:00
2019-08-04 00:00:00+00:00
2019-08-05 00:00:00+00:00
2019-08-06 00:00:00+00:00
...                                        ...
2021-08-22 00:00:00+00:00
2021-08-23 00:00:00+00:00
2021-08-24 00:00:00+00:00
2021-08-25 00:00:00+00:00
2021-08-26 00:00:00+00:00  1430765728890859524

[756 rows x 1 columns]

In [186]:
tweet_list = []
for date in merged_spikes_df.index:
    spikes_in_date_range = filter_by_previous_dates(spikes_df, date, DATES_DELTA)
    auth_tweets_in_date_range = spikes_in_date_range.join(auth_tweets, how='inner')
    tweet_list.append(auth_tweets_in_date_range[['id']])
print(tweet_list)
# auth_tweets_in_date_range

    mIndex  volume  sentiment sign   id
id     NaN     NaN        NaN  NaN  NaN

In [ ]:
auth_tweets.to_csv('data/authority_filtered/auth_tweets.csv')

In [ ]:
auth_tweets_df.to_csv('data/authority_filtered/auth_tweets' + '_' + END_DATE + '_delta_' + str(DATES_DELTA) + '.csv')
auth_tweets_df[['text', 'user_name','date_index', 'mIndex_x']].to_csv('data/authority_filtered/auth_tweets_text.csv')

KeyError: "None of [Index(['text', 'user_name', 'date_index', 'mIndex_x'], dtype='object')] are in the [columns]"

In [ ]:
filter_by_previous_dates(auth_filtered_df, END_DATE, DATES_DELTA)

2019-10-16

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
78,32336,twitter,1184699734516289537,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Lâad Italia dellâazienda cuneese: Â«AÂ fine mese...,https://t.co/yLYaHtrSGB,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-17 05:16:42+00:00

In [ ]:
DATASET = pd.read_csv(DATASET_PATH + 'ferrero_corp_preprocessed.csv')
df = DATASET.copy()
df.set_index('id', inplace=True)
df

C:\Users\alxau\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (45) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,social,topic_id,rule_id,is_comment,text,links,mentions,hashtags,media,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
id,,,,,,,,,,,,,,,,,,,,,
1156790362859548672,37450,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"#Miliardari - Giovanni Ferrero, Leonardo Del ...",https://t.co/1Qqt1xE0W2,@berlusconi,#miliardari,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 04:54:49+00:00
1156813511156256775,37449,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,#Arte e #comunicazione aziendale: lo strano r...,https://t.co/Anv1ZB6b2d,@enrica_ferrero,"#arte, #comunicazione",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 06:26:48+00:00
1156825180045492224,37448,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Cessione #Sampdoria, Gazzetta dello Sport: ""Ba...",https://t.co/vjy88qcA1o,@calcioweb,"#sampdoria, #ferrero, #vialli",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 07:13:10+00:00
1156832449571278849,37447,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Cessione Sampdoria Gazzetta dello Sport: âBall...,https://t.co/iuLZt9qNW0,NaN,"#cessione, #sampdoria, #gazzetta, #dello",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 07:42:03+00:00
1156837153432854530,37446,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, 140 milioni per la suaÂ Sampdoria http...","https://t.co/qhYUKnpesY, https://t.co/RDZjCDNvyG",NaN,NaN,https://pbs.twimg.com/media/EA3pQqVWsAAOhuo.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 08:00:45+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431211661151637508,4,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@eIa_madonna PerchÃ© ""ferrero""? ?",NaN,@eia_madonna,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:07:05+00:00
1431216680806621186,3,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@Osvaldo88322280 Un poâ le tengo per me, il re...",NaN,@osvaldo88322280,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:27:02+00:00
1431222843627409409,2,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@gippu1 Preferivi lo stile Commisso, ok? O que...",NaN,@gippu1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:51:31+00:00
1431237450085584898,1,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,E dicono di essere pure di sinistra! Ma come r...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 12:49:33+00:00
1431245619771871235,0,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@LudXsky Ferrero Rocher, talento, ouro branco ...",NaN,@ludxsky,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 13:22:01+00:00

In [ ]:
auth_filtered_df = AUTH_FILTERED_DATASET.copy()
auth_filtered_df['date_index'] = pd.to_datetime(auth_filtered_df['date_index'])
auth_filtered_df

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
0,34648,twitter,1174618145786650624,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,La Ferrero riconosce a 6000 dipendenti un prem...,https://t.co/T3wBQLWAeo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-19 09:36:03+00:00
1,34065,twitter,1176441842096910336,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Il Ministro Fioramonti si permette di giustifi...,NaN,@lofioramonti,NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-24 10:22:47+00:00
2,33847,twitter,1176748033066844160,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@theoddmother @lofioramonti In Italia la Ferre...,NaN,"@theoddmother, @lofioramonti",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-25 06:39:28+00:00
3,32534,twitter,1183821988437135362,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@gianni_la_marca @angelofilippi Per il mercato...,NaN,"@gianni_la_marca, @angelofilippi",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-10-14 19:08:51+00:00
4,32064,twitter,1186949229438263297,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Siamo in un pericoloso paradosso con il Paese ...,https://t.co/lkkYO9w8VC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-23 10:15:23+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1013,twitter,1418810115445166080,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, la strategia green del big di Alba (Ã¨...","https://t.co/r2XvO05KdN, https://t.co/t8k8vmUlQk",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-24 05:47:46+00:00
279,841,twitter,1420717382830415880,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Ferrero l'azienda meglio percepita sul territo...,"https://t.co/4O4c31bPiq, https://t.co/n8RpxZP5Vu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-29 12:06:34+00:00
280,822,twitter,1421105542945202182,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Lâattimo fuggente, online il numero di agosto ...",https://t.co/Q9FPElZrOU,"@ferrero_eu, @generali, @prada, @armani, @ciro...","#luigicremonini, #vincenzocremonini, #alberton...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30 13:48:58+00:00
281,467,twitter,1426075939201421313,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Mediobanca, Gavio arrotonda la quota. I Ferrer...","https://t.co/QPX7deAYBt, https://t.co/XUfJMFKsFE",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-13 06:59:33+00:00
282,61,twitter,1430765728890859524,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Da anni le aziende alimentari prendono impegni...,"https://t.co/79pL8eW8Dm, https://t.co/3MC4xgol6A",@foodwatch_de,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26 05:35:06+00:00

In [ ]:
filter_by_previous_dates(df, END_DATE, DATES_DELTA)

2019-10-16

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_country_code,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating
date_index,,,,,,,,,,,,,,,,,,,,,
2019-10-16 00:02:37+00:00,32417,twitter,1184258306870779904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Kinder-Ferrero : RIDATECI GLI HAPPY HIPPO - Fi...,https://t.co/hPxMjB3C4T,@changeitalia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 01:26:57+00:00,32416,twitter,1184279529105317889,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@Mar_Ferrero_91 iiio a tiiii https://t.co/Ibqt...,https://t.co/Ibqt6XunfG,@mar_ferrero_91,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 02:47:37+00:00,32415,twitter,1184299831327637504,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Gelato / Ice Cream bonanza, all for me! ?? Pis...",https://t.co/E8u9efgmKY,NaN,"#cravings, #sweettooth",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 03:01:49+00:00,32414,twitter,1184303403465433088,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Kinder-Ferrero : RIDATECI GLI HAPPY HIPPO - Fi...,https://t.co/Op1F1dBKNj,@changeitalia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 03:10:36+00:00,32413,twitter,1184305613343473664,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@emilianoavanti Ti meriti Ferrero o Lotito. Da...,NaN,@emilianoavanti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-10-22 18:47:12+00:00,32084,twitter,1186715646035410945,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Pronti a spalmare noccioleti ""da Macerata in s...",https://t.co/At5Rn8nqco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:03:11+00:00,32083,twitter,1186734767917715456,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Chiaramente, dopo la Whirlpool Di Maio intende...",NaN,NaN,#dimartedi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:13:06+00:00,32082,twitter,1186737260596731904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@DavideRosato2 La Nutella Ã¨ italiana della fer...,NaN,@daviderosato2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:16:03+00:00,32081,twitter,1186738006394363904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@diMartedi @luigidimaio Prodotti delle multina...,NaN,"@dimartedi, @luigidimaio",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 21:08:26+00:00,32080,twitter,1186751188303302659,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,...giovedÃ¬ 24/10/2019 alle 21.00 presso il Pic...,https://t.co/F2cTQSoXbO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ValueError: Lengths must match to compare