In [1]:
import pandas as pd
import datetime
from datetime import timedelta

In [2]:
DATASET_PATH = 'data/'
AUTH_FILTERED_PATH = 'data/authority_filtered/'
SPIKES_PATH = 'data/spikes/'

In [3]:
AUTH_FILTERED_DATASET = pd.read_csv(AUTH_FILTERED_PATH + 'ferrero_corp_auth.csv')
SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_spikes.csv')
AUTH_SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_auth_spikes.csv')
MERGED_SPIKES_DATASET = pd.read_csv(SPIKES_PATH + 'ferrero_corp_merged.csv')

START_DATE = '2019-12-1'
END_DATE = '2019-12-7'
DATES_DELTA = 7

In [4]:
auth_filtered_df = AUTH_FILTERED_DATASET.copy()
auth_filtered_df['date_index'] = pd.to_datetime(auth_filtered_df['date_index'])
# auth_filtered_df.set_index('id', inplace=True)
auth_filtered_df

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
0,34648,twitter,1174618145786650624,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,La Ferrero riconosce a 6000 dipendenti un prem...,https://t.co/T3wBQLWAeo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-19 09:36:03+00:00
1,34065,twitter,1176441842096910336,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Il Ministro Fioramonti si permette di giustifi...,NaN,@lofioramonti,NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-24 10:22:47+00:00
2,33847,twitter,1176748033066844160,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@theoddmother @lofioramonti In Italia la Ferre...,NaN,"@theoddmother, @lofioramonti",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-25 06:39:28+00:00
3,32534,twitter,1183821988437135362,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@gianni_la_marca @angelofilippi Per il mercato...,NaN,"@gianni_la_marca, @angelofilippi",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-10-14 19:08:51+00:00
4,32064,twitter,1186949229438263297,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Siamo in un pericoloso paradosso con il Paese ...,https://t.co/lkkYO9w8VC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-23 10:15:23+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1013,twitter,1418810115445166080,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, la strategia green del big di Alba (Ã¨...","https://t.co/r2XvO05KdN, https://t.co/t8k8vmUlQk",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-24 05:47:46+00:00
279,841,twitter,1420717382830415880,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Ferrero l'azienda meglio percepita sul territo...,"https://t.co/4O4c31bPiq, https://t.co/n8RpxZP5Vu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-29 12:06:34+00:00
280,822,twitter,1421105542945202182,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Lâattimo fuggente, online il numero di agosto ...",https://t.co/Q9FPElZrOU,"@ferrero_eu, @generali, @prada, @armani, @ciro...","#luigicremonini, #vincenzocremonini, #alberton...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30 13:48:58+00:00
281,467,twitter,1426075939201421313,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Mediobanca, Gavio arrotonda la quota. I Ferrer...","https://t.co/QPX7deAYBt, https://t.co/XUfJMFKsFE",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-13 06:59:33+00:00
282,61,twitter,1430765728890859524,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Da anni le aziende alimentari prendono impegni...,"https://t.co/79pL8eW8Dm, https://t.co/3MC4xgol6A",@foodwatch_de,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26 05:35:06+00:00

In [5]:
spikes_df = SPIKES_DATASET.copy()
spikes_df['date_index'] = pd.to_datetime(spikes_df['date_index'])
spikes_df.set_index('date_index', inplace=True)
spikes_df

                              mIndex  volume  sentiment   sign
date_index
2019-08-20 00:00:00+00:00   2.602240      96   0.373657  False
2019-08-21 00:00:00+00:00  13.554951     378   0.373657  False
2019-08-22 00:00:00+00:00   5.825910     179   0.373657  False
2019-08-23 00:00:00+00:00   2.485722      93   0.373657  False
2019-08-24 00:00:00+00:00   1.006199      71   0.373657  False
...                              ...     ...        ...    ...
2021-08-19 00:00:00+00:00   0.774941      36   0.524922   True
2021-08-20 00:00:00+00:00   0.858849      38   0.493919  False
2021-08-23 00:00:00+00:00   2.040529      67   0.468272  False
2021-08-24 00:00:00+00:00   1.287879      49   0.360722  False
2021-08-25 00:00:00+00:00   0.679956      41   0.437569  False

[165 rows x 4 columns]

In [6]:
auth_spikes_df = AUTH_SPIKES_DATASET.copy()
auth_spikes_df.set_index('date_index', inplace=True)
auth_spikes_df

                             mIndex  volume  sentiment   sign
date_index
2019-10-17 00:00:00+00:00  1.100317       1   0.600317   True
2019-10-23 00:00:00+00:00  1.411402       1   0.088598  False
2019-10-24 00:00:00+00:00  5.524376       3   0.395125  False
2019-10-25 00:00:00+00:00  1.182024       2   0.317976  False
2019-10-30 00:00:00+00:00  1.289454       1   0.789454   True
2019-10-31 00:00:00+00:00  3.668820       2   0.277060  False
2019-11-08 00:00:00+00:00  2.393225       3   0.696613   True
2019-12-01 00:00:00+00:00  3.318031       2   0.393990  False
2019-12-06 00:00:00+00:00  5.530052       6   0.393990  False
2019-12-10 00:00:00+00:00  2.212021       3   0.393990  False
2019-12-13 00:00:00+00:00  1.106010       2   0.393990  False
2019-12-24 00:00:00+00:00  1.036259       2   0.463741  False
2020-02-08 00:00:00+00:00  1.496028       1   0.003972  False
2020-02-10 00:00:00+00:00  1.017680       1   0.482320  False
2020-02-13 00:00:00+00:00  1.463476       1   0.963476   True
2020-02-18 00:00:00+00:00  1.106010       2   0.393990  False
2020-02-19 00:00:00+00:00  3.318031       4   0.393990  False
2020-02-21 00:00:00+00:00  1.106010       1   0.393990  False
2020-05-09 00:00:00+00:00  1.380941       1   0.880941   True
2020-05-14 00:00:00+00:00  1.447140       1   0.052860  False
2020-10-08 00:00:00+00:00  3.318031       2   0.393990  False
2021-03-27 00:00:00+00:00  1.106010       1   0.393990  False
2021-04-16 00:00:00+00:00  1.106010       1   0.393990  False
2021-04-19 00:00:00+00:00  1.106010       2   0.393990  False
2021-06-04 00:00:00+00:00  1.475816       1   0.024184  False

In [7]:
merged_spikes_df = MERGED_SPIKES_DATASET.copy()
merged_spikes_df.set_index('date_index', inplace=True)
merged_spikes_df

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-08-20 00:00:00+00:00,2.602240,96,0.373657,False,0.0,0.0,NaN,False
2019-08-21 00:00:00+00:00,13.554951,378,0.373657,False,0.0,1.0,0.39399,False
2019-08-22 00:00:00+00:00,5.825910,179,0.373657,False,0.0,1.0,0.39399,False
2019-08-23 00:00:00+00:00,2.485722,93,0.373657,False,0.0,1.0,0.39399,False
2019-08-24 00:00:00+00:00,1.006199,71,0.373657,False,0.0,0.0,NaN,False
...,...,...,...,...,...,...,...,...
2021-08-19 00:00:00+00:00,0.774941,36,0.524922,True,0.0,0.0,NaN,False
2021-08-20 00:00:00+00:00,0.858849,38,0.493919,False,0.0,0.0,NaN,False
2021-08-23 00:00:00+00:00,2.040529,67,0.468272,False,0.0,0.0,NaN,False
2021-08-24 00:00:00+00:00,1.287879,49,0.360722,False,0.0,0.0,NaN,False
2021-08-25 00:00:00+00:00,0.679956,41,0.437569,False,0.0,0.0,NaN,False

In [8]:
def get_relevance_idxs(df, thresh):
    return df[df['mIndex'] > thresh][['mIndex', 'sign']]


def filter_by_relevance_idxs(df, col='mIndex', thresh=0.5):
    return df[df[col] > thresh]


def get_date_range(date, d_range):
    date_list = []
    date_list.append(date)
    for day in range(1, d_range+1):
        b_date = (date - datetime.timedelta(days = day))
        a_date = (date + datetime.timedelta(days = day))
        date_list.append(b_date)
        date_list.append(a_date)
        date_list.sort()
    return date_list


# The cast needs to be handled more elegantly
def filter_by_previous_dates(df, date, date_range, col=None, formatted=False):
    formatted_date = pd.to_datetime(date, format='%Y/%m/%d', errors='coerce')
    mindate = (formatted_date - pd.to_timedelta(date_range, unit='days')).date()
    if(not formatted):
        mindate = str(mindate)
    if (col is None):
        lowerbound = df[df.index > mindate]    
        return lowerbound[lowerbound.index < date]
    else:
        lowerbound = df[df[col] > mindate]  
        return lowerbound[lowerbound[col] < formatted_date]


def get_previous_dates(date, date_range):
    date_list = []
    date_list.append(date)
    for day in range(1, date_range+1):
        b_date = (date - datetime.timedelta(days = day))
        date_list.append(b_date)
        date_list.sort()
    return date_list


# def get_volumes_in_range(df, days_range):
#     spikes = get_days_left(iris_join, 0.5)
#     days_range = timedelta(days=days_range)
#     for date in spikes['date_index']:


def filter_by_date_range(dataset, mindate, maxdate, col=None):
    formatted_mindate = pd.to_datetime(mindate, format='%Y/%m/%d', errors='coerce').date()
    formatted_maxdate = pd.to_datetime(maxdate, format='%Y/%m/%d', errors='coerce').date()
    if (col is None):
        lowerbound = dataset[dataset.index > formatted_mindate]    
        return lowerbound[lowerbound.index < formatted_maxdate]
    else:
        lowerbound = dataset[dataset[col] > formatted_mindate]    
        return lowerbound[lowerbound[col] < formatted_maxdate]


def convert_datetime_col_to_iso_format(df, col='date_index'):
    df[col] = df[col].apply(lambda x: pd.to_datetime(x, format='%Y/%m/%d', errors='coerce').date())

In [9]:
date = pd.to_datetime(END_DATE)
date_range = get_previous_dates(date, 7)
date_range_idx = pd.to_datetime(date_range, utc=True)
date_range_idx = pd.DataFrame(date_range_idx, columns=['date'])
date_range_idx

                       date
0 2019-11-30 00:00:00+00:00
1 2019-12-01 00:00:00+00:00
2 2019-12-02 00:00:00+00:00
3 2019-12-03 00:00:00+00:00
4 2019-12-04 00:00:00+00:00
5 2019-12-05 00:00:00+00:00
6 2019-12-06 00:00:00+00:00
7 2019-12-07 00:00:00+00:00

In [10]:
# filtered_merged_spikes_df = filter_by_date_range(merged_spikes_df, START_DATE, END_DATE)
filtered_merged_spikes_df = filter_by_previous_dates(merged_spikes_df, END_DATE, 7)
filtered_merged_spikes_df

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-11-30 00:00:00+00:00,1.537547,149,0.373657,False,0.000000,2.0,0.39399,False
2019-12-02 00:00:00+00:00,0.719843,109,0.373657,False,0.000000,0.0,NaN,False
2019-12-05 00:00:00+00:00,1.109779,135,0.373657,False,0.000000,1.0,0.39399,False
2019-12-06 00:00:00+00:00,30.556067,1969,0.373657,False,5.530052,6.0,0.39399,False
2019-12-07 00:00:00+00:00,6.867057,550,0.373657,False,0.000000,1.0,0.39399,False
2019-12-08 00:00:00+00:00,0.809559,165,0.373657,False,0.000000,0.0,NaN,False
2019-12-15 00:00:00+00:00,1.764587,251,0.350697,False,0.000000,1.0,0.39399,False
2019-12-22 00:00:00+00:00,1.823775,158,0.067770,False,0.000000,0.0,NaN,False

In [11]:
filter_by_relevance_idxs(merged_spikes_df, 'mIndex_x', 0.5)

,mIndex_x,volume_x,sentiment_x,sign_x,mIndex_y,volume_y,sentiment_y,sign_y
date_index,,,,,,,,
2019-08-20 00:00:00+00:00,2.602240,96,0.373657,False,0.0,0.0,NaN,False
2019-08-21 00:00:00+00:00,13.554951,378,0.373657,False,0.0,1.0,0.39399,False
2019-08-22 00:00:00+00:00,5.825910,179,0.373657,False,0.0,1.0,0.39399,False
2019-08-23 00:00:00+00:00,2.485722,93,0.373657,False,0.0,1.0,0.39399,False
2019-08-24 00:00:00+00:00,1.006199,71,0.373657,False,0.0,0.0,NaN,False
...,...,...,...,...,...,...,...,...
2021-08-19 00:00:00+00:00,0.774941,36,0.524922,True,0.0,0.0,NaN,False
2021-08-20 00:00:00+00:00,0.858849,38,0.493919,False,0.0,0.0,NaN,False
2021-08-23 00:00:00+00:00,2.040529,67,0.468272,False,0.0,0.0,NaN,False
2021-08-24 00:00:00+00:00,1.287879,49,0.360722,False,0.0,0.0,NaN,False
2021-08-25 00:00:00+00:00,0.679956,41,0.437569,False,0.0,0.0,NaN,False

In [12]:
convert_datetime_col_to_iso_format(auth_filtered_df)
auth_filtered_df

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
0,34648,twitter,1174618145786650624,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,La Ferrero riconosce a 6000 dipendenti un prem...,https://t.co/T3wBQLWAeo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-19
1,34065,twitter,1176441842096910336,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Il Ministro Fioramonti si permette di giustifi...,NaN,@lofioramonti,NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-24
2,33847,twitter,1176748033066844160,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@theoddmother @lofioramonti In Italia la Ferre...,NaN,"@theoddmother, @lofioramonti",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-25
3,32534,twitter,1183821988437135362,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@gianni_la_marca @angelofilippi Per il mercato...,NaN,"@gianni_la_marca, @angelofilippi",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-10-14
4,32064,twitter,1186949229438263297,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Siamo in un pericoloso paradosso con il Paese ...,https://t.co/lkkYO9w8VC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1013,twitter,1418810115445166080,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, la strategia green del big di Alba (Ã¨...","https://t.co/r2XvO05KdN, https://t.co/t8k8vmUlQk",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-24
279,841,twitter,1420717382830415880,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Ferrero l'azienda meglio percepita sul territo...,"https://t.co/4O4c31bPiq, https://t.co/n8RpxZP5Vu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-29
280,822,twitter,1421105542945202182,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Lâattimo fuggente, online il numero di agosto ...",https://t.co/Q9FPElZrOU,"@ferrero_eu, @generali, @prada, @armani, @ciro...","#luigicremonini, #vincenzocremonini, #alberton...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30
281,467,twitter,1426075939201421313,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Mediobanca, Gavio arrotonda la quota. I Ferrer...","https://t.co/QPX7deAYBt, https://t.co/XUfJMFKsFE",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-13
282,61,twitter,1430765728890859524,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Da anni le aziende alimentari prendono impegni...,"https://t.co/79pL8eW8Dm, https://t.co/3MC4xgol6A",@foodwatch_de,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26

In [13]:
spikes_df = spikes_df.copy().reset_index()
convert_datetime_col_to_iso_format(spikes_df)
spikes_df

     date_index     mIndex  volume  sentiment   sign
0    2019-08-20   2.602240      96   0.373657  False
1    2019-08-21  13.554951     378   0.373657  False
2    2019-08-22   5.825910     179   0.373657  False
3    2019-08-23   2.485722      93   0.373657  False
4    2019-08-24   1.006199      71   0.373657  False
..          ...        ...     ...        ...    ...
160  2021-08-19   0.774941      36   0.524922   True
161  2021-08-20   0.858849      38   0.493919  False
162  2021-08-23   2.040529      67   0.468272  False
163  2021-08-24   1.287879      49   0.360722  False
164  2021-08-25   0.679956      41   0.437569  False

[165 rows x 5 columns]

In [19]:
spikes_auth_df = spikes_df.merge(auth_filtered_df, on='date_index')

TypeError: set_index() missing 1 required positional argument: 'keys'

In [15]:
# id and username of authority tweets posted on a spike day
spike_auth_tweets = spikes_auth_df[['date_index', 'id', 'user_username']]
spike_auth_tweets

     date_index                   id    user_username
0    2019-08-21  1163965966323109889    MilanoFinanza
1    2019-08-22  1164639655574196224       repubblica
2    2019-08-23  1164947272284672001  fattoquotidiano
3    2019-09-18  1174264995162599426         Corriere
4    2019-09-18  1174293258714808321    MilanoFinanza
..          ...                  ...              ...
135  2021-06-01  1399674473960206336       repubblica
136  2021-06-01  1399707442536095744    Affaritaliani
137  2021-06-01  1399733841699520517    ItaliaaTavola
138  2021-07-20  1417393591022936065       ilgiornale
139  2021-07-21  1417876798998732810      LegaSalvini

[140 rows x 3 columns]

In [16]:
spike_auth_tweets.to_csv('data/authority_filtered/auth_tweets.csv')

In [18]:
filter_by_previous_dates(spike_auth_tweets, END_DATE, DATES_DELTA, 'date_index', formatted=True)

    date_index                   id    user_username
32  2019-12-05  1202583411128320000            ADUC1
33  2019-12-06  1202907937200627719  matteosalvinimi
34  2019-12-06  1203005958793973760    GuidoCrosetto
35  2019-12-06  1203010130884907009      NFratoianni
36  2019-12-06  1202870147297562629  stanzaselvaggia
37  2019-12-06  1202901039147618304     LucaBizzarri
38  2019-12-06  1202842418485305344   giornalettismo

In [38]:
def get_all_spikes_content(df_spikes, df_spike_tweets, dates_delta=7):
    spike_dates = {'spike_date': [], 'id': [], 'auth_username': []}
    spike_tweets_df = {}
    for date in df_spikes.index:
        spike_dates['spike_date'].append(date)
        spike_tweets_df = filter_by_previous_dates(df_spike_tweets, date, dates_delta, 'date_index', formatted=True)
        spike_tweets = {'id': [], 'auth_username': []}
        for tweet in spike_tweets_df:
            spike_tweets['id'].append(tweet['id'])
            spike_tweets['auth_username'].append(tweet['user_username'])
        spike_dates['id', 'auth_username'].append(spike_tweets)
    return pd.DataFrame(spike_dates, index=spike_dates)

SyntaxError: invalid syntax (<ipython-input-38-bc7b96e1d3f2>, line 4)

In [37]:
print(get_all_spikes_content(spikes_df, spike_auth_tweets))

IndexError: list assignment index out of range

In [ ]:
auth_tweets_df.to_csv('data/authority_filtered/auth_tweets' + '_' + END_DATE + '_delta_' + str(DATES_DELTA) + '.csv')
auth_tweets_df[['text', 'user_name','date_index', 'mIndex_x']].to_csv('data/authority_filtered/auth_tweets_text.csv')

KeyError: "None of [Index(['text', 'user_name', 'date_index', 'mIndex_x'], dtype='object')] are in the [columns]"

In [ ]:
filter_by_previous_dates(auth_filtered_df, END_DATE, DATES_DELTA, 'date_index')

<class 'datetime.date'>
<class 'datetime.date'>
<class 'pandas.core.frame.DataFrame'>

TypeError: '<' not supported between instances of 'datetime.date' and 'str'

In [ ]:
DATASET = pd.read_csv(DATASET_PATH + 'ferrero_corp_preprocessed.csv')
df = DATASET.copy()
df.set_index('id', inplace=True)
df

C:\Users\alxau\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (45) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,social,topic_id,rule_id,is_comment,text,links,mentions,hashtags,media,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
id,,,,,,,,,,,,,,,,,,,,,
1156790362859548672,37450,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"#Miliardari - Giovanni Ferrero, Leonardo Del ...",https://t.co/1Qqt1xE0W2,@berlusconi,#miliardari,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 04:54:49+00:00
1156813511156256775,37449,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,#Arte e #comunicazione aziendale: lo strano r...,https://t.co/Anv1ZB6b2d,@enrica_ferrero,"#arte, #comunicazione",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 06:26:48+00:00
1156825180045492224,37448,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Cessione #Sampdoria, Gazzetta dello Sport: ""Ba...",https://t.co/vjy88qcA1o,@calcioweb,"#sampdoria, #ferrero, #vialli",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 07:13:10+00:00
1156832449571278849,37447,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Cessione Sampdoria Gazzetta dello Sport: âBall...,https://t.co/iuLZt9qNW0,NaN,"#cessione, #sampdoria, #gazzetta, #dello",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 07:42:03+00:00
1156837153432854530,37446,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, 140 milioni per la suaÂ Sampdoria http...","https://t.co/qhYUKnpesY, https://t.co/RDZjCDNvyG",NaN,NaN,https://pbs.twimg.com/media/EA3pQqVWsAAOhuo.jpg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-08-01 08:00:45+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431211661151637508,4,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@eIa_madonna PerchÃ© ""ferrero""? ?",NaN,@eia_madonna,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:07:05+00:00
1431216680806621186,3,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@Osvaldo88322280 Un poâ le tengo per me, il re...",NaN,@osvaldo88322280,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:27:02+00:00
1431222843627409409,2,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@gippu1 Preferivi lo stile Commisso, ok? O que...",NaN,@gippu1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 11:51:31+00:00
1431237450085584898,1,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,E dicono di essere pure di sinistra! Ma come r...,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 12:49:33+00:00
1431245619771871235,0,twitter,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"@LudXsky Ferrero Rocher, talento, ouro branco ...",NaN,@ludxsky,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-27 13:22:01+00:00

In [ ]:
auth_filtered_df = AUTH_FILTERED_DATASET.copy()
auth_filtered_df['date_index'] = pd.to_datetime(auth_filtered_df['date_index'])
auth_filtered_df

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating,date_index
0,34648,twitter,1174618145786650624,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,La Ferrero riconosce a 6000 dipendenti un prem...,https://t.co/T3wBQLWAeo,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-09-19 09:36:03+00:00
1,34065,twitter,1176441842096910336,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Il Ministro Fioramonti si permette di giustifi...,NaN,@lofioramonti,NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-24 10:22:47+00:00
2,33847,twitter,1176748033066844160,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@theoddmother @lofioramonti In Italia la Ferre...,NaN,"@theoddmother, @lofioramonti",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-09-25 06:39:28+00:00
3,32534,twitter,1183821988437135362,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@gianni_la_marca @angelofilippi Per il mercato...,NaN,"@gianni_la_marca, @angelofilippi",NaN,...,41.898417,12.545146,41.898417,12.545146,NaN,NaN,NaN,NaN,NaN,2019-10-14 19:08:51+00:00
4,32064,twitter,1186949229438263297,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Siamo in un pericoloso paradosso con il Paese ...,https://t.co/lkkYO9w8VC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-10-23 10:15:23+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,1013,twitter,1418810115445166080,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Ferrero, la strategia green del big di Alba (Ã¨...","https://t.co/r2XvO05KdN, https://t.co/t8k8vmUlQk",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-24 05:47:46+00:00
279,841,twitter,1420717382830415880,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Ferrero l'azienda meglio percepita sul territo...,"https://t.co/4O4c31bPiq, https://t.co/n8RpxZP5Vu",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-29 12:06:34+00:00
280,822,twitter,1421105542945202182,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Lâattimo fuggente, online il numero di agosto ...",https://t.co/Q9FPElZrOU,"@ferrero_eu, @generali, @prada, @armani, @ciro...","#luigicremonini, #vincenzocremonini, #alberton...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-07-30 13:48:58+00:00
281,467,twitter,1426075939201421313,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Mediobanca, Gavio arrotonda la quota. I Ferrer...","https://t.co/QPX7deAYBt, https://t.co/XUfJMFKsFE",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-13 06:59:33+00:00
282,61,twitter,1430765728890859524,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Da anni le aziende alimentari prendono impegni...,"https://t.co/79pL8eW8Dm, https://t.co/3MC4xgol6A",@foodwatch_de,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021-08-26 05:35:06+00:00

In [ ]:
filter_by_previous_dates(df, END_DATE, DATES_DELTA)

2019-10-16

,Unnamed: 0,social,id,topic_id,rule_id,is_comment,text,links,mentions,hashtags,...,place_country_code,place_location_lat,place_location_lon,place_lat,place_lon,user_place_country_code,score_spam,score_performance,user_score_rank,score_rating
date_index,,,,,,,,,,,,,,,,,,,,,
2019-10-16 00:02:37+00:00,32417,twitter,1184258306870779904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Kinder-Ferrero : RIDATECI GLI HAPPY HIPPO - Fi...,https://t.co/hPxMjB3C4T,@changeitalia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 01:26:57+00:00,32416,twitter,1184279529105317889,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@Mar_Ferrero_91 iiio a tiiii https://t.co/Ibqt...,https://t.co/Ibqt6XunfG,@mar_ferrero_91,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 02:47:37+00:00,32415,twitter,1184299831327637504,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Gelato / Ice Cream bonanza, all for me! ?? Pis...",https://t.co/E8u9efgmKY,NaN,"#cravings, #sweettooth",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 03:01:49+00:00,32414,twitter,1184303403465433088,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,Kinder-Ferrero : RIDATECI GLI HAPPY HIPPO - Fi...,https://t.co/Op1F1dBKNj,@changeitalia,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-16 03:10:36+00:00,32413,twitter,1184305613343473664,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@emilianoavanti Ti meriti Ferrero o Lotito. Da...,NaN,@emilianoavanti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-10-22 18:47:12+00:00,32084,twitter,1186715646035410945,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Pronti a spalmare noccioleti ""da Macerata in s...",https://t.co/At5Rn8nqco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:03:11+00:00,32083,twitter,1186734767917715456,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,"Chiaramente, dopo la Whirlpool Di Maio intende...",NaN,NaN,#dimartedi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:13:06+00:00,32082,twitter,1186737260596731904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@DavideRosato2 La Nutella Ã¨ italiana della fer...,NaN,@daviderosato2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 20:16:03+00:00,32081,twitter,1186738006394363904,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,@diMartedi @luigidimaio Prodotti delle multina...,NaN,"@dimartedi, @luigidimaio",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-10-22 21:08:26+00:00,32080,twitter,1186751188303302659,7ee62d5c-5811-45ce-9cef-c09d143f041a,12559.0,False,...giovedÃ¬ 24/10/2019 alle 21.00 presso il Pic...,https://t.co/F2cTQSoXbO,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ValueError: Lengths must match to compare